#!/bin/bash
CONFIG_EXISTS=0
if [ -n "$(docker ps -q -f name=dev-setup_refinery-config_1)" ]
then
    if [ "$( docker container inspect -f '{{.State.Status}}' dev-setup_refinery-config_1 )" == "running" ]; 
    then
        CONFIG_EXISTS=1
    fi
elif [ -n "$(docker ps -q -f name=dev-setup-refinery-config-1)" ]
then
    if [ "$( docker container inspect -f '{{.State.Status}}' dev-setup-refinery-config-1 )" == "running" ]; 
    then
        CONFIG_EXISTS=1
    fi
else
    if [ -n "$(docker ps -q -f name=refinery-config)" ];
    then
        if [ "$( docker container inspect -f '{{.State.Status}}' refinery-config )" == "running" ];
        then
            CONFIG_EXISTS=1
        fi
    fi
fi
if [ $CONFIG_EXISTS -eq 0 ]
then 
    echo "refinery-config couldn't be found - exit"
    exit 1
else
    echo "refinery-config found -> proceeding"
fi

